### ISSUE TITLE
CinemaMod 1.20.4 works? Yes, but not fully

### ISSUE THREAD

**Issue by h3nda** [CinemaMod/CinemaMod#16]
Hello there, I got CinemaMod working on MC 1.20.4 with Java 17 with editing Manifest and fabric.mod.json files
![image](https://github.com/user-attachments/assets/9ba2db05-5014-4922-8bd3-10a76f46b8cd)
But also, when I'm trying to open settings with command /video settings I get a crash with 
```
---- Minecraft Crash Report ----
// You're mean.

Time: 2024-07-15 16:54:29
Description: Rendering screen

java.lang.NoSuchMethodError: 'void net.minecraft.class_437.method_25420(net.minecraft.class_332)'
	at com.cinemamod.fabric.gui.VideoSettingsScreen.method_25420(VideoSettingsScreen.java:89)
	at com.cinemamod.fabric.gui.VideoSettingsScreen.method_25394(VideoSettingsScreen.java:99)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$261(class_757.java)
	at net.minecraft.class_757.wrapOperation$zoj000$fabric-screen-api-v1$onRenderScreen(class_757.java:2611)
	at net.minecraft.class_757.method_3192(class_757.java:931)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.cinemamod.fabric.gui.VideoSettingsScreen.method_25420(VideoSettingsScreen.java:89)
	at com.cinemamod.fabric.gui.VideoSettingsScreen.method_25394(VideoSettingsScreen.java:99)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$261(class_757.java)
	at net.minecraft.class_757.wrapOperation$zoj000$fabric-screen-api-v1$onRenderScreen(class_757.java:2611)

-- Screen render details --
Details:
	Screen name: com.cinemamod.fabric.gui.VideoSettingsScreen
	Mouse location: Scaled: (420, 244). Absolute: (840.000000, 489.000000)
	Screen size: Scaled: (840, 490). Absolute: (1680, 979). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:931)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Uptime --
Details:
	JVM uptime: 384.345s
	Wall uptime: 361.977s
	High-res time: 350.698s
	Client ticks: 6805 ticks / 340.250s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:908)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```
Theoretically, CinemaMod requires a little fix to work correctly on 1.20.4. So, waiting for completed release <3
